### PR TITLE
added config option

### PR DESCRIPTION
**Pull request by ronaldlokers**
- Added the option to set the sass and css folders in the grunt config
  file so you don't have to create a separate compass configuration file
- updated the read me to reflect these changes

### CODE REVIEW

**Comment by khalillechelt** [comment]
Awesome! Will have a look at this as soon as I can. Thanks.

## 

Sent from my iPhone

Am Samstag, 2. Juni 2012 um 21:29 schrieb Ronald Lokers:

**Comment by ronaldlokers** [comment]
The compass help is not very clear on what you can set from the command-line, but I just found out how you can set the "output style" from the command-line:

```
compass compile --output-style compressed
```

I will add this functionality soon so that there is no need anymore for a separate compass config file!

**Comment by khalillechelt** [comment]
Coo, great idea! Best would be if you were able to config the compass tasks with the different output modes so that you can have a min and an expanded file generated at the same time 

## 

Sent from my iPhone

Am Samstag, 2. Juni 2012 um 23:14 schrieb Ronald Lokers:

**Comment by ronaldlokers** [comment]
That should be possible, the "concat" plugin can also handle multiple calls. So we can look at that task to see how it's done.

**Comment by khalillechelt** [comment]
Yep. Good idea. 

## 

Sent from my iPhone

Am Samstag, 2. Juni 2012 um 23:58 schrieb Ronald Lokers:

**Pull request merged**
