### PR TITLE
Added in basePath parameter

### PR DESCRIPTION
**Pull request by mindmelting**
Added a parameter to allow compass to compile in a specified directory. Useful for when grunt is being used with multiple projects with multiple folder structures.

### CODE REVIEW

**Comment by khalillechelt** [comment]
Please check why the Travis build failed and fix it.

**Comment by mindmelting** [comment]
Tests are fine locally, only fails on Travis on the 'specify' test which I have not modified.

**Comment by khalillechelt** [comment]
Ok I will look into it.

**Comment by mindmelting** [comment]
Cool, just cloned both your master, and my forked master and they both build fine, so not really sure why it is failing on the 'specify' test. Thanks

**Comment by khalillechelt** [comment]
Yo @mindmelting curious thing: the Travic CI test failed because apparently the files are sorted the other way round when stored on the Travis file system. The test executes the minimatch command that reads all filenames in a directory. On travis it comes out as `test/test.scss test/other.scss` and on my Mac it reads `test/other.scss test/test.scss`. Weird. So I just took that test out.

**Comment by khalillechelt** [comment]
Your changes are merged and published in the NPM repository.

**Comment by mindmelting** [comment]
Very odd. Thanks for the merge should be useful for others too :)

**Comment by khalillechelt** [comment]
Yep. Thanks for the PR dude!

**Pull request merged**
