### PR TITLE
Remove grunt as a dependency

### PR DESCRIPTION
**Pull request by shama**
Hi! Could we remove grunt as a dependency? This way additional unneeded local copies of grunt isn't installed with each project that uses grunt-compass. Thanks!

### CODE REVIEW

**Comment by khalillechelt** [comment]
Hi. No I am not removing the dependency for now. Since that is how you are supposed to make grunt plugins.

**Comment by shama** [comment]
Specifying grunt as dependency is only necessary to lock `grunt-compass` to a specific version of Grunt.

Your plugin, as is, works with both v0.3.12 and 0.4.0a. I also personally promise to ensure `grunt-compass` works with both v0.3 and v0.4 the day 0.4 is released. So please? :D

```
$ grunt
Running "compass:dev" (compass) task
`compass compile --sass-dir="scss" --css-dir="css" --images-dir="/path/to/images" --debug-info --relative-assets --force` was initiated.

COMPASS output:
   create css/test.css 

Done, without errors.
$ grunt --version
grunt v0.4.0a
$ ls node_modules/grunt-compass/node_modules/
$ 
```

**Comment by khalillechelt** [comment]
I think I read that in grunt 0.4.0 grunt dependency will be removed from gruntplugins. Once that version is out and I can verify that. I will remove the dependency.

**Comment by shama** [comment]
Cool, thank you!

**Comment by doctyper** [comment]
+1. Having just run `grunt init:gruntplugin`, the default settings do not list `grunt` as a dependency in the generated `package.json`.

@kahill can you reconsider?

**Comment by khalillechelt** [comment]
sure, will verify and take it out :)  

Am Dienstag, 11. September 2012 um 20:24 schrieb Richard Herrera:

**Comment by khalillechelt** [comment]
Dependency is removed.

**Comment by shama** [comment]
\o/ Thanks!

**Pull request closed without merging**
