### PR TITLE
Add config option

### PR DESCRIPTION
**Pull request by jcassee**
See issue #13.

### CODE REVIEW

**Comment by khalillechelt** [comment]
Thx.
Can you change the Readme accordingly to discribe how to use that option? What path is the config-path relative to?

**Comment by khalillechelt** [comment]
Thanks! Will merge soon.

**Comment by jcassee** [comment]
It would be great if this change made it to the NPM registry. Would make explaining setting up our development environment to my coworkers much easier! :-)

**Comment by khalillechelt** [comment]
Oh man, so sorry. I was kinda busy. Taking care of that now...

**Comment by khalillechelt** [comment]
Done.

**Comment by jcassee** [comment]
Great, thanks!

**Pull request merged**
